### PR TITLE
Option for duration and language.

### PR DESCRIPTION
**Pull request by Abhi0725**
User is given option for Daily/weekly/monthly or yearly horoscope. Moreover user can also select the language of the horoscope (english or hindi).

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
The options for duration are working for English but not for Hindi. Did you tested it?

Nothing is working for the Hindi part. While the URL generated is fine, but I'm getting an IndexError: list index out of range for all option of durations for Hindi. Either this is because of the unicode that you want to read or because of some issues in where exactly is the hindi para is located, as Beautiful soup is reading it from the source.

One more thing, please look how the spacing between the operator and operands is done, add a new line after the function ends, add space after arguments in function call. Follow proper indentation. You can make other lines cleaner too.

Please resolve these issues, I'll be happy to merge the pull.

**Comment by Abhi0725** [comment]
The problem with Hindi option may be due to absence of hindi font in PC (as it is working fine for me).

**Comment by tapaswenipathak** [comment]
@Abhi0725 Can you please resolve the merge conflicts?

**Comment by Abhi0725** [comment]
@tapasweni-pathak really busy these days. I will resolve merge issues in few days.

**Comment by tapaswenipathak** [comment]
Reopen when resolved or feel free to submit a fresh pull request.

**Pull request closed without merging**
